package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	goSort "sort"
	"time"

	"github.com/wricardo/tesla-road-trip-game/game/engine"
	"github.com/wricardo/tesla-road-trip-game/game/service"
	"github.com/wricardo/tesla-road-trip-game/graph/generated"
	"github.com/wricardo/tesla-road-trip-game/graph/model"
)

// Layout is the resolver for the layout field.
func (r *gameMapResolver) Layout(ctx context.Context, obj *model.GameMap, password *string) ([]string, error) {
	policyAny, ok := gameMapLayoutPolicy.Load(obj)
	if !ok {
		return obj.Layout, nil
	}
	policy, ok := policyAny.(gridPolicy)
	if !ok || !policy.fogEnabled {
		return obj.Layout, nil
	}
	if password == nil || *password != policy.gridPassword {
		return nil, fmt.Errorf("forbidden: map layout password required when fog mode is enabled")
	}
	return obj.Layout, nil
}

// Grid is the resolver for the grid field.
func (r *gameStateResolver) Grid(ctx context.Context, obj *model.GameState, password *string) ([][]*model.Cell, error) {
	policyAny, ok := gameStateGridPolicy.Load(obj)
	if !ok {
		return obj.Grid, nil
	}
	policy, ok := policyAny.(gridPolicy)
	if !ok || !policy.fogEnabled {
		return obj.Grid, nil
	}
	if password == nil || *password != policy.gridPassword {
		return nil, fmt.Errorf("forbidden: grid password required when fog mode is enabled")
	}
	return obj.Grid, nil
}

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, mapID *string, mapName *string, fogEnabled *bool, fogRadius *int, gridPassword *string, moveDelayMs *int) (*model.Session, error) {
	id := ""
	if mapID != nil {
		id = *mapID
	} else if mapName != nil {
		id = *mapName
	}
	opts := service.CreateSessionOptions{}
	if fogEnabled != nil {
		opts.FogEnabled = *fogEnabled
	}
	if fogRadius != nil {
		opts.FogRadius = *fogRadius
	}
	if gridPassword != nil {
		opts.GridPassword = *gridPassword
	}
	if moveDelayMs != nil {
		opts.MoveDelayMs = moveDelayMs
	}
	s, err := r.Service.CreateSession(ctx, id, opts)
	if err != nil {
		return nil, err
	}
	return toSession(s), nil
}

// DeleteSession is the resolver for the deleteSession field.
func (r *mutationResolver) DeleteSession(ctx context.Context, id string) (*model.DeleteSessionResult, error) {
	if err := r.Service.DeleteSession(ctx, id); err != nil {
		return nil, err
	}
	return &model.DeleteSessionResult{Message: fmt.Sprintf("Session %s deleted", id)}, nil
}

// UpdateSession is the resolver for the updateSession field.
func (r *mutationResolver) UpdateSession(ctx context.Context, id string, displayName string) (*model.Session, error) {
	s, err := r.Service.UpdateSessionDisplayName(ctx, id, displayName)
	if err != nil {
		return nil, err
	}
	return toSession(s), nil
}

// Move is the resolver for the move field.
func (r *mutationResolver) Move(ctx context.Context, sessionID string, direction model.Direction, reset *bool) (*model.MoveResult, error) {
	resetValue := false
	if reset != nil {
		resetValue = *reset
	}
	result, err := r.Service.Move(ctx, sessionID, directionString(direction), resetValue)
	if err != nil {
		return nil, err
	}
	if r.Hub != nil {
		delayMs := 0
		if result.GameState != nil {
			delayMs = result.GameState.MoveDelayMs
		}
		if delayMs > 0 {
			select {
			case <-ctx.Done():
				return nil, ctx.Err()
			case <-time.After(time.Duration(delayMs) * time.Millisecond):
			}
		}
		r.Hub.BroadcastToSession(sessionID, result.GameState)
	}
	return toMoveResult(result), nil
}

// BulkMove is the resolver for the bulkMove field.
func (r *mutationResolver) BulkMove(ctx context.Context, sessionID string, moves []model.Direction, reset *bool) (*model.BulkMoveResult, error) {
	resetValue := false
	if reset != nil {
		resetValue = *reset
	}
	dirs := make([]string, len(moves))
	for i, move := range moves {
		dirs[i] = directionString(move)
	}
	state, err := r.Service.GetGameState(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	delayMs := state.MoveDelayMs
	if delayMs > 0 {
		return r.bulkMoveWithStepBroadcast(ctx, sessionID, dirs, resetValue, time.Duration(delayMs)*time.Millisecond)
	}
	result, err := r.Service.BulkMove(ctx, sessionID, dirs, resetValue)
	if err != nil {
		return nil, err
	}
	if r.Hub != nil {
		r.Hub.BroadcastToSession(sessionID, result.GameState)
	}
	return toBulkResult(result), nil
}

// Reset is the resolver for the reset field.
func (r *mutationResolver) Reset(ctx context.Context, sessionID string) (*model.GameState, error) {
	state, err := r.Service.Reset(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	if r.Hub != nil {
		r.Hub.BroadcastToSession(sessionID, state)
	}
	return toGameState(state), nil
}

// CreateMap is the resolver for the createMap field.
func (r *mutationResolver) CreateMap(ctx context.Context, name string, mapArg model.GameMapInput) (*model.GameMap, error) {
	if err := checkAdminKey(ctx); err != nil {
		return nil, err
	}
	cfg := fromGameMapInput(mapArg)
	if cfg.Name == "" {
		cfg.Name = name
	}
	if err := r.Service.SaveMap(ctx, name, cfg); err != nil {
		return nil, err
	}
	return toGameMap(cfg), nil
}

// UpdateMap is the resolver for the updateMap field.
func (r *mutationResolver) UpdateMap(ctx context.Context, name string, patch model.GameMapPatchInput) (*model.GameMap, error) {
	if err := checkAdminKey(ctx); err != nil {
		return nil, err
	}
	cfg, err := r.Service.LoadMap(ctx, name)
	if err != nil {
		return nil, fmt.Errorf("map %q not found: %w", name, err)
	}
	applyPatch(cfg, patch)
	if err := r.Service.SaveMap(ctx, name, cfg); err != nil {
		return nil, err
	}
	return toGameMap(cfg), nil
}

// ValidateMap is the resolver for the validateMap field.
func (r *mutationResolver) ValidateMap(ctx context.Context, mapArg model.GameMapInput) (*model.MapValidationResult, error) {
	cfg := fromGameMapInput(mapArg)
	if cfg.Name == "" {
		cfg.Name = mapArg.Name
	}
	if err := engine.ValidateGameConfig(cfg); err != nil {
		errMsg := err.Error()
		return &model.MapValidationResult{
			Valid:    false,
			Winnable: false,
			Message:  errMsg,
			Error:    &errMsg,
		}, nil
	}
	return &model.MapValidationResult{
		Valid:    true,
		Winnable: true,
		Message:  fmt.Sprintf("Map %q is solvable.", cfg.Name),
	}, nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*model.Session, error) {
	s, err := r.Service.GetSession(ctx, id)
	if err != nil {
		return nil, err
	}
	return toSession(s), nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, sort *model.SessionSort, order *model.SortOrder, limit *int) (*model.SessionList, error) {
	sessions, err := r.Service.ListSessions(ctx)
	if err != nil {
		return nil, err
	}
	sortName := "accessed"
	if sort != nil && *sort == model.SessionSortCreated {
		sortName = "created"
	}
	orderName := "desc"
	if order != nil && *order == model.SortOrderAsc {
		orderName = "asc"
	}
	goSort.Slice(sessions, func(i, j int) bool {
		ti, tj := sessions[i].LastAccessedAt, sessions[j].LastAccessedAt
		if sortName == "created" {
			ti, tj = sessions[i].CreatedAt, sessions[j].CreatedAt
		}
		if orderName == "asc" {
			return ti.Before(tj)
		}
		return ti.After(tj)
	})
	total := len(sessions)
	if limit != nil && *limit > 0 && *limit < len(sessions) {
		sessions = sessions[:*limit]
	}
	out := make([]*model.Session, len(sessions))
	for i, s := range sessions {
		out[i] = toSession(s)
	}
	return &model.SessionList{Count: len(out), Total: total, Sessions: out, Sort: sortName, Order: orderName}, nil
}

// UnifiedSessions is the resolver for the unifiedSessions field.
func (r *queryResolver) UnifiedSessions(ctx context.Context, mapName *string) (*model.UnifiedSessions, error) {
	sessions, err := r.Service.ListSessions(ctx)
	if err != nil {
		return nil, err
	}
	if mapName != nil && *mapName != "" {
		filtered := make([]*service.SessionInfo, 0)
		for _, s := range sessions {
			if s.MapName == *mapName {
				filtered = append(filtered, s)
			}
		}
		sessions = filtered
	}
	name := ""
	if len(sessions) > 0 {
		name = sessions[0].MapName
	} else if mapName != nil {
		name = *mapName
	}
	out := make([]*model.UnifiedSession, len(sessions))
	for i, s := range sessions {
		out[i] = toUnifiedSession(s)
	}
	return &model.UnifiedSessions{MapName: name, Count: len(out), Sessions: out}, nil
}

// GameState is the resolver for the gameState field.
func (r *queryResolver) GameState(ctx context.Context, sessionID string) (*model.GameState, error) {
	state, err := r.Service.GetGameState(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	return toGameState(state), nil
}

// History is the resolver for the history field.
func (r *queryResolver) History(ctx context.Context, sessionID string, page *int, limit *int, order *model.SortOrder) (*model.HistoryResponse, error) {
	opts := service.HistoryOptions{Page: 1, Limit: 50, Order: "desc"}
	if page != nil {
		opts.Page = *page
	}
	if limit != nil {
		opts.Limit = *limit
	}
	if order != nil && *order == model.SortOrderAsc {
		opts.Order = "asc"
	}
	h, err := r.Service.GetMoveHistory(ctx, sessionID, opts)
	if err != nil {
		return nil, err
	}
	return toHistory(h), nil
}

// Maps is the resolver for the maps field.
func (r *queryResolver) Maps(ctx context.Context) ([]*model.MapInfo, error) {
	maps, err := r.Service.ListMaps(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.MapInfo, len(maps))
	for i, m := range maps {
		out[i] = toMapInfo(m)
	}
	return out, nil
}

// Map is the resolver for the map field.
func (r *queryResolver) Map(ctx context.Context, name string, password *string) (*model.GameMap, error) {
	if err := checkUIMapPassword(password); err != nil {
		return nil, err
	}
	cfg, err := r.Service.LoadMap(ctx, name)
	if err != nil {
		return nil, err
	}
	return toGameMap(cfg), nil
}

// SessionUpdated is the resolver for the sessionUpdated field.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, sessionID string) (<-chan *model.GameState, error) {
	if r.Hub == nil {
		return nil, fmt.Errorf("subscriptions unavailable: no hub")
	}
	engineCh := r.Hub.SubscribeSession(ctx, sessionID)
	out := make(chan *model.GameState, 8)
	go func() {
		defer close(out)
		for state := range engineCh {
			out <- toGameState(state)
		}
	}()
	return out, nil
}

// LobbyUpdated is the resolver for the lobbyUpdated field.
func (r *subscriptionResolver) LobbyUpdated(ctx context.Context) (<-chan *model.GameState, error) {
	if r.Hub == nil {
		return nil, fmt.Errorf("subscriptions unavailable: no hub")
	}
	engineCh := r.Hub.SubscribeLobby(ctx)
	out := make(chan *model.GameState, 32)
	go func() {
		defer close(out)
		for state := range engineCh {
			out <- toGameState(state)
		}
	}()
	return out, nil
}

// GameMap returns generated.GameMapResolver implementation.
func (r *Resolver) GameMap() generated.GameMapResolver { return &gameMapResolver{r} }

// GameState returns generated.GameStateResolver implementation.
func (r *Resolver) GameState() generated.GameStateResolver { return &gameStateResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type gameMapResolver struct{ *Resolver }
type gameStateResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
