package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"fmt"
	goSort "sort"

	"github.com/wricardo/tesla-road-trip-game/game/service"
	"github.com/wricardo/tesla-road-trip-game/graph/generated"
	"github.com/wricardo/tesla-road-trip-game/graph/model"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, configID *string, configName *string) (*model.Session, error) {
	id := ""
	if configID != nil {
		id = *configID
	} else if configName != nil {
		id = *configName
	}
	s, err := r.Service.CreateSession(ctx, id)
	if err != nil {
		return nil, err
	}
	return toSession(s), nil
}

// DeleteSession is the resolver for the deleteSession field.
func (r *mutationResolver) DeleteSession(ctx context.Context, id string) (*model.DeleteSessionResult, error) {
	if err := r.Service.DeleteSession(ctx, id); err != nil {
		return nil, err
	}
	return &model.DeleteSessionResult{Message: fmt.Sprintf("Session %s deleted", id)}, nil
}

// Move is the resolver for the move field.
func (r *mutationResolver) Move(ctx context.Context, sessionID string, direction model.Direction, reset *bool) (*model.MoveResult, error) {
	resetValue := false
	if reset != nil {
		resetValue = *reset
	}
	result, err := r.Service.Move(ctx, sessionID, directionString(direction), resetValue)
	if err != nil {
		return nil, err
	}
	if r.Hub != nil {
		r.Hub.BroadcastToSession(sessionID, result.GameState)
	}
	return toMoveResult(result), nil
}

// BulkMove is the resolver for the bulkMove field.
func (r *mutationResolver) BulkMove(ctx context.Context, sessionID string, moves []model.Direction, reset *bool) (*model.BulkMoveResult, error) {
	resetValue := false
	if reset != nil {
		resetValue = *reset
	}
	dirs := make([]string, len(moves))
	for i, move := range moves {
		dirs[i] = directionString(move)
	}
	result, err := r.Service.BulkMove(ctx, sessionID, dirs, resetValue)
	if err != nil {
		return nil, err
	}
	if r.Hub != nil {
		r.Hub.BroadcastToSession(sessionID, result.GameState)
	}
	return toBulkResult(result), nil
}

// Reset is the resolver for the reset field.
func (r *mutationResolver) Reset(ctx context.Context, sessionID string) (*model.GameState, error) {
	state, err := r.Service.Reset(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	if r.Hub != nil {
		r.Hub.BroadcastToSession(sessionID, state)
	}
	return toGameState(state), nil
}

// CreateConfig is the resolver for the createConfig field.
func (r *mutationResolver) CreateConfig(ctx context.Context, name string, config model.GameConfigInput) (*model.GameConfig, error) {
	cfg := fromGameConfigInput(config)
	if cfg.Name == "" {
		cfg.Name = name
	}
	if err := r.Service.SaveConfig(ctx, name, cfg); err != nil {
		return nil, err
	}
	return toGameConfig(cfg), nil
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id string) (*model.Session, error) {
	s, err := r.Service.GetSession(ctx, id)
	if err != nil {
		return nil, err
	}
	return toSession(s), nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, sort *model.SessionSort, order *model.SortOrder, limit *int) (*model.SessionList, error) {
	sessions, err := r.Service.ListSessions(ctx)
	if err != nil {
		return nil, err
	}
	sortName := "accessed"
	if sort != nil && *sort == model.SessionSortCreated {
		sortName = "created"
	}
	orderName := "desc"
	if order != nil && *order == model.SortOrderAsc {
		orderName = "asc"
	}
	goSort.Slice(sessions, func(i, j int) bool {
		ti, tj := sessions[i].LastAccessedAt, sessions[j].LastAccessedAt
		if sortName == "created" {
			ti, tj = sessions[i].CreatedAt, sessions[j].CreatedAt
		}
		if orderName == "asc" {
			return ti.Before(tj)
		}
		return ti.After(tj)
	})
	total := len(sessions)
	if limit != nil && *limit > 0 && *limit < len(sessions) {
		sessions = sessions[:*limit]
	}
	out := make([]*model.Session, len(sessions))
	for i, s := range sessions {
		out[i] = toSession(s)
	}
	return &model.SessionList{Count: len(out), Total: total, Sessions: out, Sort: sortName, Order: orderName}, nil
}

// UnifiedSessions is the resolver for the unifiedSessions field.
func (r *queryResolver) UnifiedSessions(ctx context.Context, configName *string) (*model.UnifiedSessions, error) {
	sessions, err := r.Service.ListSessions(ctx)
	if err != nil {
		return nil, err
	}
	if configName != nil && *configName != "" {
		filtered := make([]*service.SessionInfo, 0)
		for _, s := range sessions {
			if s.ConfigName == *configName {
				filtered = append(filtered, s)
			}
		}
		sessions = filtered
	}
	name := ""
	if len(sessions) > 0 {
		name = sessions[0].ConfigName
	} else if configName != nil {
		name = *configName
	}
	out := make([]*model.UnifiedSession, len(sessions))
	for i, s := range sessions {
		out[i] = toUnifiedSession(s)
	}
	return &model.UnifiedSessions{ConfigName: name, Count: len(out), Sessions: out}, nil
}

// GameState is the resolver for the gameState field.
func (r *queryResolver) GameState(ctx context.Context, sessionID string) (*model.GameState, error) {
	state, err := r.Service.GetGameState(ctx, sessionID)
	if err != nil {
		return nil, err
	}
	return toGameState(state), nil
}

// History is the resolver for the history field.
func (r *queryResolver) History(ctx context.Context, sessionID string, page *int, limit *int, order *model.SortOrder) (*model.HistoryResponse, error) {
	opts := service.HistoryOptions{Page: 1, Limit: 50, Order: "desc"}
	if page != nil {
		opts.Page = *page
	}
	if limit != nil {
		opts.Limit = *limit
	}
	if order != nil && *order == model.SortOrderAsc {
		opts.Order = "asc"
	}
	h, err := r.Service.GetMoveHistory(ctx, sessionID, opts)
	if err != nil {
		return nil, err
	}
	return toHistory(h), nil
}

// Configs is the resolver for the configs field.
func (r *queryResolver) Configs(ctx context.Context) ([]*model.ConfigInfo, error) {
	configs, err := r.Service.ListConfigs(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ConfigInfo, len(configs))
	for i, c := range configs {
		out[i] = toConfigInfo(c)
	}
	return out, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context, name string) (*model.GameConfig, error) {
	cfg, err := r.Service.LoadConfig(ctx, name)
	if err != nil {
		return nil, err
	}
	return toGameConfig(cfg), nil
}

// SessionUpdated is the resolver for the sessionUpdated field.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, sessionID string) (<-chan *model.GameState, error) {
	if r.Hub == nil {
		return nil, fmt.Errorf("subscriptions unavailable: no hub")
	}
	engineCh := r.Hub.SubscribeSession(ctx, sessionID)
	out := make(chan *model.GameState, 8)
	go func() {
		defer close(out)
		for state := range engineCh {
			out <- toGameState(state)
		}
	}()
	return out, nil
}

// LobbyUpdated is the resolver for the lobbyUpdated field.
func (r *subscriptionResolver) LobbyUpdated(ctx context.Context) (<-chan *model.GameState, error) {
	if r.Hub == nil {
		return nil, fmt.Errorf("subscriptions unavailable: no hub")
	}
	engineCh := r.Hub.SubscribeLobby(ctx)
	out := make(chan *model.GameState, 32)
	go func() {
		defer close(out)
		for state := range engineCh {
			out <- toGameState(state)
		}
	}()
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
