// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AttemptInfo struct {
	X        int    `json:"x"`
	Y        int    `json:"y"`
	TileChar string `json:"tileChar"`
	TileType string `json:"tileType"`
	Passable bool   `json:"passable"`
}

type BulkMoveResult struct {
	MovesExecuted  int          `json:"movesExecuted"`
	TotalMoves     int          `json:"totalMoves"`
	RequestedMoves int          `json:"requestedMoves"`
	Success        bool         `json:"success"`
	GameState      *GameState   `json:"gameState"`
	Events         []*GameEvent `json:"events"`
	StoppedReason  string       `json:"stoppedReason"`
	StopReasonCode string       `json:"stopReasonCode"`
	StoppedOnMove  int          `json:"stoppedOnMove"`
	Truncated      bool         `json:"truncated"`
	Limit          int          `json:"limit"`
	StartPos       *Position    `json:"startPos"`
	EndPos         *Position    `json:"endPos"`
	StartBattery   int          `json:"startBattery"`
	EndBattery     int          `json:"endBattery"`
	ScoreDelta     int          `json:"scoreDelta"`
	Steps          []*StepInfo  `json:"steps"`
	AttemptedTo    *AttemptInfo `json:"attemptedTo,omitempty"`
	GameOver       bool         `json:"gameOver"`
	GameOverCode   string       `json:"gameOverCode"`
	Message        string       `json:"message"`
	PossibleMoves  []string     `json:"possibleMoves"`
	LocalView3x3   []string     `json:"localView3x3"`
	BatteryRisk    string       `json:"batteryRisk"`
}

type Cell struct {
	Type    string `json:"type"`
	Visited bool   `json:"visited"`
	ID      string `json:"id"`
}

type ConfigInfo struct {
	Filename    string `json:"filename"`
	ConfigID    string `json:"configId"`
	Name        string `json:"name"`
	Description string `json:"description"`
	GridSize    int    `json:"gridSize"`
	MaxBattery  int    `json:"maxBattery"`
}

type ConfigMessages struct {
	Welcome            string `json:"welcome"`
	HomeCharge         string `json:"homeCharge"`
	SuperchargerCharge string `json:"superchargerCharge"`
	ParkVisited        string `json:"parkVisited"`
	ParkAlreadyVisited string `json:"parkAlreadyVisited"`
	Victory            string `json:"victory"`
	OutOfBattery       string `json:"outOfBattery"`
	Stranded           string `json:"stranded"`
	CantMove           string `json:"cantMove"`
	BatteryStatus      string `json:"batteryStatus"`
	HitWall            string `json:"hitWall"`
}

type ConfigMessagesInput struct {
	Welcome            string `json:"welcome"`
	HomeCharge         string `json:"homeCharge"`
	SuperchargerCharge string `json:"superchargerCharge"`
	ParkVisited        string `json:"parkVisited"`
	ParkAlreadyVisited string `json:"parkAlreadyVisited"`
	Victory            string `json:"victory"`
	OutOfBattery       string `json:"outOfBattery"`
	Stranded           string `json:"stranded"`
	CantMove           string `json:"cantMove"`
	BatteryStatus      string `json:"batteryStatus"`
	HitWall            string `json:"hitWall"`
}

type DeleteSessionResult struct {
	Message string `json:"message"`
}

type GameConfig struct {
	Name              string          `json:"name"`
	Description       string          `json:"description"`
	GridSize          int             `json:"gridSize"`
	MaxBattery        int             `json:"maxBattery"`
	StartingBattery   int             `json:"startingBattery"`
	Layout            []string        `json:"layout"`
	Legend            []*LegendEntry  `json:"legend"`
	WallCrashEndsGame bool            `json:"wallCrashEndsGame"`
	Messages          *ConfigMessages `json:"messages"`
}

type GameConfigInput struct {
	Name              string               `json:"name"`
	Description       string               `json:"description"`
	GridSize          int                  `json:"gridSize"`
	MaxBattery        int                  `json:"maxBattery"`
	StartingBattery   int                  `json:"startingBattery"`
	Layout            []string             `json:"layout"`
	Legend            []*LegendEntryInput  `json:"legend"`
	WallCrashEndsGame bool                 `json:"wallCrashEndsGame"`
	Messages          *ConfigMessagesInput `json:"messages"`
}

type GameEvent struct {
	Type      string    `json:"type"`
	Message   string    `json:"message"`
	Timestamp string    `json:"timestamp"`
	Position  *Position `json:"position"`
}

type GameState struct {
	Grid              [][]*Cell           `json:"grid"`
	PlayerPos         *Position           `json:"playerPos"`
	Battery           int                 `json:"battery"`
	MaxBattery        int                 `json:"maxBattery"`
	Score             int                 `json:"score"`
	VisitedParks      []*VisitedPark      `json:"visitedParks"`
	Message           string              `json:"message"`
	GameOver          bool                `json:"gameOver"`
	Victory           bool                `json:"victory"`
	ConfigName        string              `json:"configName"`
	MoveHistory       []*MoveHistoryEntry `json:"moveHistory"`
	TotalMoves        int                 `json:"totalMoves"`
	LocalView         []*SurroundingCell  `json:"localView"`
	CurrentMoves      []*MoveHistoryEntry `json:"currentMoves"`
	CurrentMovesCount int                 `json:"currentMovesCount"`
	LocalView3x3      []string            `json:"localView3x3"`
	BatteryRisk       string              `json:"batteryRisk"`
}

type HistoryResponse struct {
	Moves       []*MoveHistoryEntry `json:"moves"`
	TotalMoves  int                 `json:"totalMoves"`
	Page        int                 `json:"page"`
	PageSize    int                 `json:"pageSize"`
	TotalPages  int                 `json:"totalPages"`
	HasNext     bool                `json:"hasNext"`
	HasPrevious bool                `json:"hasPrevious"`
}

type LegendEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LegendEntryInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type MoveHistoryEntry struct {
	Action       string    `json:"action"`
	FromPosition *Position `json:"fromPosition"`
	ToPosition   *Position `json:"toPosition"`
	Battery      int       `json:"battery"`
	Timestamp    int       `json:"timestamp"`
	Success      bool      `json:"success"`
	MoveNumber   int       `json:"moveNumber"`
}

type MoveResult struct {
	Success     bool         `json:"success"`
	GameState   *GameState   `json:"gameState"`
	Message     string       `json:"message"`
	Events      []*GameEvent `json:"events"`
	Step        *StepInfo    `json:"step,omitempty"`
	AttemptedTo *AttemptInfo `json:"attemptedTo,omitempty"`
}

type Mutation struct {
}

type Position struct {
	X int `json:"x"`
	Y int `json:"y"`
}

type Query struct {
}

type Session struct {
	ID             string      `json:"id"`
	ConfigName     string      `json:"configName"`
	CreatedAt      string      `json:"createdAt"`
	LastAccessedAt string      `json:"lastAccessedAt"`
	GameState      *GameState  `json:"gameState"`
	GameConfig     *GameConfig `json:"gameConfig"`
}

type SessionList struct {
	Count    int        `json:"count"`
	Total    int        `json:"total"`
	Sessions []*Session `json:"sessions"`
	Sort     string     `json:"sort"`
	Order    string     `json:"order"`
}

type StepInfo struct {
	Idx           int       `json:"idx"`
	Dir           string    `json:"dir"`
	From          *Position `json:"from"`
	To            *Position `json:"to"`
	TileChar      string    `json:"tileChar"`
	TileType      string    `json:"tileType"`
	BatteryBefore int       `json:"batteryBefore"`
	BatteryAfter  int       `json:"batteryAfter"`
	Success       bool      `json:"success"`
	Charged       bool      `json:"charged"`
	Park          bool      `json:"park"`
	Victory       bool      `json:"victory"`
}

type SurroundingCell struct {
	X    int    `json:"x"`
	Y    int    `json:"y"`
	Type string `json:"type"`
}

type UnifiedSession struct {
	SessionID      string      `json:"sessionId"`
	CreatedAt      string      `json:"createdAt"`
	LastAccessedAt string      `json:"lastAccessedAt"`
	GameState      *GameState  `json:"gameState"`
	GameConfig     *GameConfig `json:"gameConfig"`
}

type UnifiedSessions struct {
	ConfigName string            `json:"configName"`
	Count      int               `json:"count"`
	Sessions   []*UnifiedSession `json:"sessions"`
}

type VisitedPark struct {
	ID      string `json:"id"`
	Visited bool   `json:"visited"`
}

type Direction string

const (
	DirectionUp    Direction = "UP"
	DirectionDown  Direction = "DOWN"
	DirectionLeft  Direction = "LEFT"
	DirectionRight Direction = "RIGHT"
)

var AllDirection = []Direction{
	DirectionUp,
	DirectionDown,
	DirectionLeft,
	DirectionRight,
}

func (e Direction) IsValid() bool {
	switch e {
	case DirectionUp, DirectionDown, DirectionLeft, DirectionRight:
		return true
	}
	return false
}

func (e Direction) String() string {
	return string(e)
}

func (e *Direction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Direction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Direction", str)
	}
	return nil
}

func (e Direction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Direction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Direction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionSort string

const (
	SessionSortCreated  SessionSort = "CREATED"
	SessionSortAccessed SessionSort = "ACCESSED"
)

var AllSessionSort = []SessionSort{
	SessionSortCreated,
	SessionSortAccessed,
}

func (e SessionSort) IsValid() bool {
	switch e {
	case SessionSortCreated, SessionSortAccessed:
		return true
	}
	return false
}

func (e SessionSort) String() string {
	return string(e)
}

func (e *SessionSort) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionSort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionSort", str)
	}
	return nil
}

func (e SessionSort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionSort) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionSort) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
