import { gql, type Client } from '@urql/svelte';
import { CREATE_SESSION_MUTATION, UPDATE_SESSION_MUTATION } from '$lib/queries';

// Same default as the home page's Advanced options: lets spectators follow fast AI moves.
export const DEFAULT_MOVE_DELAY_MS = 300;

export type CreateOptions = {
	mapID: string;
	name?: string;
	fogEnabled?: boolean;
	fogRadius?: number;
	gridPassword?: string;
	moveDelayMs?: number;
};

/** Creates a session (and names it) and returns its id; throws with the server message on failure. */
export async function createGameSession(client: Client, opts: CreateOptions): Promise<string> {
	const fogEnabled = !!opts.fogEnabled;
	const result = await client
		.mutation(gql(CREATE_SESSION_MUTATION), {
			mapID: opts.mapID || null,
			fogEnabled,
			fogRadius: fogEnabled ? (opts.fogRadius ?? 1) : 1,
			gridPassword: fogEnabled && opts.gridPassword?.trim() ? opts.gridPassword : null,
			moveDelayMs: Math.trunc(opts.moveDelayMs ?? DEFAULT_MOVE_DELAY_MS)
		})
		.toPromise();
	if (result.error) throw new Error(result.error.message);
	const id: string | undefined = result.data?.createSession?.id;
	if (!id) throw new Error('The server did not return a session id');
	// A blank password with fog on is generated by the server and returned once;
	// remember it locally so the creator can still reveal the full grid on the play page.
	const generatedPassword = result.data?.createSession?.generatedGridPassword;
	if (generatedPassword) {
		try { localStorage.setItem(`fogPassword:${id}`, generatedPassword); } catch { /* storage unavailable */ }
	}
	const name = opts.name?.trim();
	if (name) await client.mutation(gql(UPDATE_SESSION_MUTATION), { id, displayName: name }).toPromise();
	return id;
}
